import type { Metadata } from "next";
import "./globals.css";
import { Navigation } from "./components/naviagtion";
import { Providers } from "./components/providers";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "ReParkr",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <Toaster />
          <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-gray-900 dark:to-gray-800">
            <Navigation />
            <main className="container mx-auto px-4 py-8">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
